# Generated by Django 6.0.1 on 2026-02-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdsong', '0008_translation_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='send_failed',
            field=models.IntegerField(default=0, verbose_name='failed count'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='send finished at'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_sent',
            field=models.IntegerField(default=0, verbose_name='sent count'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='send started at'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='total to send'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status_message',
            field=models.CharField(default='', max_length=255, verbose_name='status message'),
        ),
    ]
