# Generated by Django 6.0.1 on 2026-02-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdsong', '0009_campaign_send_failed_campaign_send_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='error message'),
        ),
    ]
