# Generated by Django 6.0.2 on 2026-02-13 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdsong', '0010_receipt_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='backend_used',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='backend used'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='error_sample',
            field=models.JSONField(blank=True, default=dict, verbose_name='recent errors'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='failure_reason',
            field=models.TextField(blank=True, default='', verbose_name='failure reason'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_progress_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last progress update'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='backend_response_code',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='backend response code'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='processed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='processed at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='ses_message_id',
            field=models.CharField(blank=True, default='', max_length=191, verbose_name='SES message id'),
        ),
    ]
